[project]
name = 'fit-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.assets-pool]
path = 'contracts/assets-pool.clar'
clarity_version = 3
epoch = 3.0

[contracts.fit-token]
path = 'contracts/fit-token.clar'
clarity_version = 3
epoch = 3.0

[contracts.user-identity]
path = 'contracts/user-identity.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
